language: node_js
node_js:
    - 0.10
notifications:
    email: false
    webhooks:
      urls:
        https://api.ghostinspector.com/v1/suites/[suite-id]/execute/?userId=5395815fa5a1cc0571c82a04&apiKey=715d0b078352cf72d0a9ccdf8c9ca5bc1abd8583
            on_success: always
            on_failure: neverbefore_install: npm install -g grunt-cli
install: npm install
